# Non-secret DB 
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: trip-planner
data:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "tripdb"
  DB_USER: "tripuser"

---
# Sensitive values DB.
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: trip-planner
type: Opaque
stringData:
  DB_PASSWORD: "dHJpcHBhc3M="
  MYSQL_ROOT_PASSWORD: "cm9vdHBhc3M="
  MYSQL_PASSWORD: "dHJpcHBhc3M="

